### ISSUE TITLE
No corresponding edge found for sink port

### ISSUE THREAD

**Issue by hmiomand** [preesm/preesm#295] opened 2020-02-24 09:14 UTC
Trying to execute the workflow in the attached project gives the error "**No corresponding edge found for sink port out4_u_3**".

![image](https://user-images.githubusercontent.com/26252258/75139624-6205b300-56ed-11ea-84fc-637e7f6bb6b4.png)

Adding passthrough actors between **Broadcast_u** and **reshape_u** on all but one fifo allows to bypass the issue.
Data-rates and data-types are set to valid values for graph evaluation.
Memory scripts are **not** used in the workflow.

[dummy_no_edge_for_sink.zip](https://github.com/preesm/preesm/files/4243684/dummy_no_edge_for_sink.zip)

**Comment by orlyn44** [comment] 2020-02-24 09:34
Could not reproduce with latest release binaries nor with the master / develop branches.
I'm closing the issue as it seems to be related to your specific configuration.

**Comment by orlyn44** [comment] 2020-02-24 13:45
apparently there IS a bug. 
Here is a minimal project reproducing the bug. 
It seems to happen when there are multiple edges coming from actor to another. 
There must be one actor in between on at least one of the edges for the bug to happen and still at least 2 edges between the two original actors.
A | -> B ->  | C
   | --------> | 
   | --------> | 
In the given exemple, if actor forward is remove there is no problem.
Also, if another actor forward is put between the broadcast and sink, there is no problem.
[issue295.zip](https://github.com/preesm/preesm/files/4244830/issue295.zip)

**Closed** 2020-02-25 14:06 UTC
Labels: bug
