### ISSUE TITLE
Error in the generated code using PAPIFY

### ISSUE THREAD

**Issue by ClaudioRubattu** [preesm/preesm#158] opened 2019-06-18 12:18 UTC
As in the attached file "error.txt", the compilation of the generated code does not succeed using the current PREESM version (release 3.8.1), when the PAPIFY monitors are considered for the stereo matching application.  
Also, the PREESM project is attached.    

[stereo_PREESM_3.8.1.zip](https://github.com/preesm/preesm/files/3301394/stereo_PREESM_3.8.1.zip)

[error.txt](https://github.com/preesm/preesm/files/3301193/error.txt)

**Comment by dmadronal** [comment] 2019-06-18 12:54
The issue is fixed in branch "fixPapifyCodeGen"

**Comment by antoine-morvan** [comment] 2019-06-18 14:32
fixed since merge of https://github.com/preesm/preesm/pull/159

**Closed by antoine-morvan** 2019-06-18 14:32 UTC
