### ISSUE TITLE
Adding config actor to the graph / java class error

### ISSUE THREAD

**Issue by alemehghasemi** [preesm/preesm#336] opened 2021-06-17 15:47 UTC
Hello everyone,

I have generated simple graph in PREESM with three actors. 
I am trying to add a reconfigurable actor to set a parameter but I received the following error.
It would be great if you can help me to solve.

****SEVERE: Unexpected Exception: java.lang.ClassCastException:class org.preesm.model.pisdf.impl.ConfigOutputPortImpl cannot be cast to class org.preesm.model.pisdf.Parameter (org.preesm.model.pisdf.impl.ConfigOutputPortImpl and org.preesm.model.pisdf.Parameter are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @239bc43f)
 Contact Preesm developers if you cannot solve the problem.****

Thank you.
BR,
Alemeh,

**Comment by ahonorat** [comment] 2021-06-17 16:00
Hello,
I tried to reproduce your bug, without success.

Could you indicate me more precisely the steps that you have followed to build the graph?
Alternatively, could you provide a MWE of a .pi file producing the error?

By the way, which version of PREESM are you using?

Best regards

**Comment by alemehghasemi** [comment] 2021-06-17 16:48
Hello ahonorat,
Thank you for your reply.
I followed the same steps explained in the tutorial 9.
I added an actor to the graph named it SliceSizeSetter.
By right click on the actor I added input port config and connected it to the parameter. (output port the same)
I set the header file as refinement.
I use PREESM version 3.21.
You can find attached my project.

Best Regards,
Alemeh,
[ForkJoin_MemScript.zip](https://github.com/preesm/preesm/files/6671860/ForkJoin_MemScript.zip)

**Comment by ahonorat** [comment] 2021-06-18 12:44
Is the following graph what you intent to have?
![preesmIssue336](https://user-images.githubusercontent.com/5851945/122562329-3c6b8e00-d043-11eb-8c24-52ded9a088bd.png)

I did not have errors while generating this graph on the last night build of Preesm. If the attached graph is what you intent to have, then I will try to reproduce on the same version as you. Interfaces (including Conf. Input) have been heavily modified in the UI and slightly in the model since last revision 3.21. It might be already fixed in the current develop branch.

**Comment by alemehghasemi** [comment] 2021-06-21 14:53
Yes Ahonorat, this is exactly the graph I am trying to generate.
So I should clone PREESM from develop branch?
Thank you for your help.

BR,
Alemeh,

**Comment by ahonorat** [comment] 2021-06-23 12:11
Hello,

sorry for the delay, I tried again with your version of Preesm (3.21) and I did not have any problem. So I am a bit surprised.
Could you try to open the attached project and regenerate the .diagram of the only .pi graph? It should be a MWE of your issue.
[TestIssue336.zip](https://github.com/preesm/preesm/files/6701663/TestIssue336.zip)

Thanks,
Alexandre H.

**Comment by ahonorat** [comment] 2021-09-14 14:06
Hello @alemehghasemi , do you still have the issue?
If no answer, I will close the issue since I cannot reproduce it.

**Comment by ahonorat** [comment] 2021-09-27 15:24
No new input, closing the issue.

**Closed as completed by ahonorat** 2021-09-27 15:24 UTC
Labels: waiting for input
