### ISSUE TITLE
Preesm 3.1.3 does not launch on macOS 10.9

### ISSUE THREAD

**Issue by jserot** [preesm/preesm#97] opened 2019-01-09 15:50 UTC
The app, downloaded from ::

https://github.com/preesm/preesm/releases/download/v3.1.3/preesm-3.1.3-macosx.cocoa.x86_64.zip

crashes at launch time 

![snap](https://user-images.githubusercontent.com/33293151/50910661-8c83a680-142e-11e9-9440-639522d5006d.png)

**Comment by antoine-morvan** [comment] 2019-01-21 12:31
Hi, 

I just tried on my Mac running Sierra (10.12.6) with java 1.8.0_181 and could not reproduce the issue. Could you provide more information ?

**Comment by antoine-morvan** [comment] 2019-01-23 09:00
By "Eclipse launcher" I mean the underlying Eclipse framework, and especially the first things that run when you start Eclipse. It is possible to update it manually, but even I do not want to try.

I will release a new version of Preesm by the end of the week, hopefully this will solve the issue.

Until then, you can build Preesm on your machine following these instructions : https://preesm.github.io/docs/buildpreesm/

**Comment by jserot** [comment] 2019-01-23 10:32
Ok, let's wait for the next release and cross fingers ;)

**Comment by antoine-morvan** [comment] 2019-01-24 09:36
I just released 3.2.0 : https://github.com/preesm/preesm/releases/tag/v3.2.0
Let me know if things get better...

**Comment by jserot** [comment] 2019-01-24 09:47
_Pas mieux_ :(
Crash log attached.
[crash.log](https://github.com/preesm/preesm/files/2791064/crash.log)

**Comment by antoine-morvan** [comment] 2019-01-25 08:41
Can you run the default Eclipse packages, as this one https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2018-12/R/eclipse-java-2018-12-R-macosx-cocoa-x86_64.dmg ?

**Comment by antoine-morvan** [comment] 2019-01-25 12:38
If we track the Eclipse updates in the release notes, we have:
 * Preesm v3.2.0: Eclipse 2018-12 (4.10)
 * Preesm v2.13.0 : Eclipse Photon (4.8)
 * Preesm v2.4.2 : Eclipse Oxygen (4.7)
So you can try going back in time using those versions. They are all available here : http://preesm.insa-rennes.fr/releases/
Although there has been some updates in the model since then, it should not impact basic examples.

**Comment by antoine-morvan** [comment] 2019-01-25 12:47
I'll close this issue since it's not directly related to our code base.

**Closed by antoine-morvan** 2019-01-25 12:47 UTC
Labels: invalid
