### ISSUE TITLE
[TUTO] Workflow task error

### ISSUE THREAD

**Issue by ggendro** [preesm/preesm#149] opened 2019-05-15 06:33 UTC
When doing tutorial Memory Footprint on the official website of Preesm, there is an error message for workflow task "DisplayGantt":
Plugin associated to the workflow task not found.	Codegen.workflow	/org.ietr.preesm.sobel/Workflows	org.ietr.preesm.mapper.plot.GanttEditor	Problem

**Comment by antoine-morvan** [comment] 2019-05-15 07:35
What version of Preesm are you using ?
Could you attach a zip with the project you are using ?

**Comment by antoine-morvan** [comment] 2019-05-15 07:42
Duplicate of #134 fixed with v3.7.0

**Closed by antoine-morvan** 2019-05-15 07:42 UTC
